### ISSUE TITLE
Space issue in Page on Mobile devices

### ISSUE THREAD

**Issue by Sunilshah-7** [WRCRoboticsClub/frontend#6]
The width of the screen should expand to the whole screen, it works fine on desktop but after device width <476px (like mobile phones) the width seems to expand only 80% of the total width. This should be a CSS error. I am using Tech Nextjs and Theme UI, here is the picture of the issue:
<img width="428" alt="image" src="https://user-images.githubusercontent.com/43769682/176215235-b5f3ff0f-26c5-490a-8161-e98edef4350c.png">

**Comment by YuilTripathee** [comment]
This looks like a problem in React domain. I'm not familiar with react. Please check the issue in this thread, which might help.

**Comment by YuilTripathee** [comment]
https://stackoverflow.com/questions/34796678/unknown-white-space-appear-on-the-right-side-of-web-page

**Comment by YuilTripathee** [comment]
![image](https://user-images.githubusercontent.com/28005756/176267264-65c14bdd-5121-4371-bd56-b418253c9b8f.png)
width changes are also disabled from DOM

**Comment by Sunilshah-7** [comment]
cool

**Comment by Sunilshah-7** [comment]
fixed
